// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FiOX-9pMxWngx3lzDblzvXAsXx8u1X8',
    appId: '1:535298455776:web:deae4119fba740e8a57885',
    messagingSenderId: '535298455776',
    projectId: 'flutter-chat-app-a484f',
    authDomain: 'flutter-chat-app-a484f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a484f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxsiJ6aCzqzHsLr0tM4SGQHjNAO6EAMAE',
    appId: '1:535298455776:android:c0685b2e70a7e8a5a57885',
    messagingSenderId: '535298455776',
    projectId: 'flutter-chat-app-a484f',
    storageBucket: 'flutter-chat-app-a484f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW2-pOHjcvHEO1HbNf06AB1J2SJxQ_sUA',
    appId: '1:535298455776:ios:7b9c23aa806dfd30a57885',
    messagingSenderId: '535298455776',
    projectId: 'flutter-chat-app-a484f',
    storageBucket: 'flutter-chat-app-a484f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW2-pOHjcvHEO1HbNf06AB1J2SJxQ_sUA',
    appId: '1:535298455776:ios:7b9c23aa806dfd30a57885',
    messagingSenderId: '535298455776',
    projectId: 'flutter-chat-app-a484f',
    storageBucket: 'flutter-chat-app-a484f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4FiOX-9pMxWngx3lzDblzvXAsXx8u1X8',
    appId: '1:535298455776:web:8fd871aa4f35ee4ea57885',
    messagingSenderId: '535298455776',
    projectId: 'flutter-chat-app-a484f',
    authDomain: 'flutter-chat-app-a484f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a484f.firebasestorage.app',
  );
}
